sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: online_delivery
    username: root
    password: abc123
  redis:
    host: localhost
    port: 6379
  wechat:
    appid: wxbea38f38cb3b6ab2
    secret: f3e21dbdb915843e2cb86f20bd8cb427
