sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: online_delivery
    username: root
    password: abc123
  redis:
    host: localhost
    port: 6379
